### ISSUE TITLE
Use output from previous transformation when switching modes

### ISSUE THREAD

**Issue by nimobeeren** [SaraVieira/css-to-js#12]
When the user starts the site, the example transforms some CSS to a JS object. When the user changes mode to e.g. "JS object => React props", the input does not change and the transformation fails. The user has to fill in a valid JS object to make it work.

It would be great if we can take the output from a "CSS => JS" transformation and use that as input for a "JS => JSX" transforrmation. That's just one example, but since we will soon be able to transform from any of the 3 formats to another, it should be possible to generate the input for any transformation mode.

This would make it very easy to switch between modes without changing the input.

**Comment by SaraVieira** [comment]
For now, we have something KINDA like this that I added so that it never fails at least and we switch the example code based on what you are transformation you are using

**Comment by nimobeeren** [comment]
Done in #19.
