### ISSUE TITLE
Disable the "Used by" button on GitHub

### ISSUE THREAD

**Issue by nimobeeren** [SaraVieira/css-to-js#13]
Right now we have this in the header:

![image](https://user-images.githubusercontent.com/12124298/77261358-3fd06800-6c8e-11ea-861f-c2d30032a339.png)

But that's referring to the npm module `css-to-js` and has nothing to do with this project. So we should probably disable that if that's somehow possible.

**Comment by SaraVieira** [comment]
From what I can see I don't thinkn it is possible :(

**Comment by leettaylor** [comment]
I believe this might have something to do with the name used in `package.json`. You could try changing the name to `"name": "@saravieira/css-to-js"`

**Comment by SaraVieira** [comment]
Interesting, I changed and still nothing :(

**Comment by SaraVieira** [comment]
It did work but delayed by a day 🎉

**Comment by nimobeeren** [comment]
Sweet :trophy:
