### ISSUE TITLE
AST transformer: CSS to JS

### ISSUE THREAD

**Issue by nimobeeren** [SaraVieira/css-to-js#36]
*For more details and suggestions for this issue, check out [the master issue](https://github.com/SaraVieira/css-to-js/issues/38).*

This issue consists of two tasks:

- Add an AST parser for CSS
- Build JS output given the AST

We would prefer to use [`postcss`](https://www.npmjs.com/package/postcss) as the parser, since we are already bundling it as a dependency of `prettier`.

**Comment by impulsivetomato** [comment]
Hey @nimobeeren. I'd like to contribute to this project :) 

I had a look at the PostCSS parser and got as far as grabbing the declarations from their AST. The next step would be to build out the JS. 

One thing I wanted to ask about is how you plan to handle units? The code below strips "px" but it feels like this should be carried over to JS, I often use rems too.
https://github.com/SaraVieira/css-to-js/blob/f753c6954190caebf3d9e1a511bb0dec50bd52e4/src/transformers/css2js.js#L182

If you're happy with the code so far I'll start on the other stuff.



```js
import { parse, Declaration, ChildNode, Root } from 'postcss';

const css: string = `
  flex: 1;
  color: rgba(255,255,255,0);
  .main {
    height: 12px;
    width: 20px;
  }
`;

function getCssProps(css: Root): Declaration[] {
  const { nodes } = css;

  if (!nodes) {
    return;
  }

  function iterate(nodes: ChildNode[], declarations: Declaration[] = []) {
    nodes.forEach((item) => {
      if (item.type === 'decl') {
        declarations.push(item);
      } else if (item.type === 'rule') {
        iterate(item.nodes, declarations);
      }
    });

    return declarations;
  }

  return iterate(nodes);
}

export function parseCss(css: string): string | Declaration[] {
  try {
    const root: Root = parse(css);
    return getCssProps(root);
  } catch (e) {
    return css;
  }
}

// Returns [Declaration, Declaration, Declaration, Declaration]
```

**Comment by nimobeeren** [comment]
Hi @impulsivetomato :wave: 

Thank you for your interest! That looks like a great start. If I had one comment it would be that I'm not sure if `parseCss` should fall back to returning a string when parsing fails. Maybe it would be better if it failed loudly by throwing.

About the units: we chose to convert pixels to numbers in JS because that worked best for us. For example, Theme UI (or rather Emotion) uses [the convention](https://theme-ui.com/guides/object-styles#numbers) of interpreting numbers as pixels, and interpreting strings as the raw CSS (including unit). What's your use case for including the `px` unit on the JS object?

I'll assign you to the issue, please keep us updated on your progress!

**Comment by impulsivetomato** [comment]
Hey @nimobeeren. Good suggestion. I'll make the change, thanks :)

Regarding units: My thinking is that the returned JS is tool-agnostic matches the inputted CSS.  But, it looks like [react converts](https://reactjs.org/docs/dom-elements.html#style) the values too. I'm not sure if this approach is used by other libraries/frameworks but I'm happy to keep the current approach.

**Comment by nimobeeren** [comment]
@impulsivetomato cool, I didn't know the React `style` prop worked like that too (I've never used it). I think for most cases keeping it unitless would be preferred.
