### ISSUE TITLE
Add some contributor roles

### ISSUE THREAD

**Issue by nimobeeren** [SaraVieira/css-to-js#39]

**Comment by nimobeeren** [comment]
@SaraVieira I think you should be listed as a contributor too, if you don't mind of course!

This project was originally your idea, you built the first code and did most of the design. 

cc @all-contributors (let's see what it makes of that

**Comment by nimobeeren** [comment]
Alright @all-contributors, please add @SaraVieira for ideas, code and design.

**Comment by nimobeeren** [comment]
@all-contributors please add @SaraVieira for ideas, code and design.

**Comment by nimobeeren** [comment]
And how about this:

@all-contributors please add @nimobeeren for ideas and project management.

**Comment by SaraVieira** [comment]
Thank you man!
